name: weather_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  geolocator: ^13.0.2
  provider: ^6.1.2
  geocoding: ^3.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/asset/image /clear.jpg
    - lib/asset/image /clear.png
    - lib/asset/image /cloud-lightning.png
    - lib/asset/image /clouds.jpg
    - lib/asset/image /clouds.png
    - lib/asset/image /drizzle.jpg
    - lib/asset/image /drizzle.png
    - lib/asset/image /few-clouds.png
    - lib/asset/image /mist.png
    - lib/asset/image /moon.png
    - lib/asset/image /rain.png
    - lib/asset/image /snow.png
    - lib/asset/image /temperature-high.png
    - lib/asset/image /temperature-low.png
    - lib/asset/image /thunder.jpg
    - lib/asset/image /sun.png
    - lib/asset/image /2940f068-d4ae-4ede-afa1-b7737084ad55.jpeg
    - lib/asset/image /b2c662f6-41ec-4341-8708-96e78698e105.jpeg
